##################################### LIST ALL #############################################
GET http://localhost:8080/article

################################
GET http://localhost:8080/client?page=1

################################
GET http://localhost:8080/commande/all

################################
GET http://localhost:8080/article/catalogue

################################
GET http://localhost:8080/categorie?page=2

################################
GET http://localhost:8080/photo

##################################### LIST ONE #############################################
GET http://localhost:8080/article/5

################################
GET http://localhost:8080/categorie/2

################################
GET http://localhost:8080/photo/2

################################
GET http://localhost:8080/photo/article/19

################################
GET http://localhost:8080/categorie/3/articles

################################
GET http://localhost:8080/client/5

################################
GET http://localhost:8080/client/1/commandes

################################
GET http://localhost:8080/commande/8

##################################### CREATE #############################################

POST http://localhost:8080/article
Accept: application/json
Content-Type: application/json 

  {
    "libelle": "Haricot (Niébé)",
    "qteStock": 150,
    "prix": 1300.0,
    "categoryId": 3,
    "newPrix": 1200,
    "note": 5,
    "isdispo": true,
    "promo": false,
    
    "description": "Le haricot niébé, aussi appelé pois à œil noir, est un ingrédient clé de la cuisine sénégalaise. Cultivé biologiquement à Thiès, il est une source essentielle de protéines végétales, idéal pour les végétariens et les amateurs de cuisine saine. Riche en fibres et en fer, il favorise une bonne digestion et renforce l’organisme. Il se déguste en sauce, en ragoût ou en accompagnement des plats de céréales."
  }

#################

POST http://localhost:8080/categorie
Accept: application/json
Content-Type: application/json

{
    "code" : "FRT_221",
    "name" : "Fruits"
},
{
    "code" : "LGM_221",
    "name" : "Legumes"
},
{
    "code" : "CRL_221",
    "name" : "Cereales"
}

#################

POST http://localhost:8080/commande
Accept: application/json
Content-Type: application/json

{
    "montant" : 12000.0,
    "clientId" : 1,
    "details" : [
        {
            "articleId" : 1,
            "qteVendu" : 2,
            "prixVente" : 1100.0
        },
        {
            "articleId" : 2,
            "qteVendu" : 3,
            "prixVente" : 1800.0
        }
    ]
}

#################

POST http://localhost:8080/client
Accept: application/json
Content-Type: application/json

{
    "name" : "Bathiezar",
    "telephone" : "775027892"
}
